name: React CI

on: [push, pull_request]

jobs:
  build:
    name: Test React App
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        working-directory: ./frontend
        run: yarn install
      - name: Build Application
        working-directory: ./frontend
        run: yarn build
      - name: Test Application
        working-directory: ./frontend
        run: yarn test
