name: React CI

on: [push, pull_request]

jobs:
  build:
    name: Test React App
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: borales/actions-yarn@v2.3.0
        working-directory: ./frontend
        run: yarn install
      - name: Build application
        uses: borales/actions-yarn@v2.3.0
        working-directory: ./frontend
        run: yarn build
      - name: Test application
        uses: borales/actions-yarn@v2.3.0
        working-directory: ./frontend
        run: yarn test
