name: 'Deploy to Production site'

on:
  push:
    branches:
      - master

jobs:
  prod-deploy-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Code that does the build process goes here
      - name: Deploy AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Sync site to S3
        run: aws s3 sync ./SourceCode/_site/ s3://wahid.tech/ --delete
      - name: Set CloudFront COMMIT_HASH variable
        run: sed -i "s/COMMIT_HASH/${GITHUB_SHA}/g" ./BuildAdditions/CloudFront-Invalidate.json
      - name: Set PRODUCTION CloudFront CLOUDFRONT_ID variable
        run: sed -i "s/CLOUDFRONT_ID/UPDATETHIS/g" ./BuildAdditions/CloudFront-Invalidate.json #TODO update the UDPATETHIS with CloudFront ID
      - name: Clear CloudFront Cache
        run: aws cloudfront create-invalidation --cli-input-json file://./BuildAdditions/CloudFront-Invalidate.json
